import { GeneratedPin, SEOContent as SEOContentType } from '@/types/recipe';
import { PinPreview } from './PinPreview';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { Download, ImageIcon, Loader2, Package } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import JSZip from 'jszip';
import { toPng } from 'html-to-image';
import { toast } from 'sonner';

interface PinGalleryProps {
  pins: GeneratedPin[];
  isGenerating: boolean;
  progress: number;
  seo?: SEOContentType;
}

export function PinGallery({ pins, isGenerating, progress, seo }: PinGalleryProps) {
  const downloadAllAsZip = async () => {
    if (pins.length === 0) return;

    try {
      const zip = new JSZip();
      const imagesFolder = zip.folder('pinterest-pins');

      // Add images
      for (let i = 0; i < pins.length; i++) {
        const pin = pins[i];
        // Get the image data
        const response = await fetch(pin.imageUrl);
        const blob = await response.blob();
        imagesFolder?.file(`pin-${pin.angle}-${i + 1}.png`, blob);
      }

      // Add SEO content as text file
      if (seo) {
        const seoContent = `Pinterest SEO Content
========================

TITLE:
${seo.title}

DESCRIPTION:
${seo.description}

HASHTAGS:
${seo.hashtags.map(h => `#${h}`).join(' ')}

========================
Generated by PinFactory AI
`;
        zip.file('pinterest-seo-content.txt', seoContent);
      }

      // Generate and download
      const content = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(content);
      const link = document.createElement('a');
      link.href = url;
      link.download = 'pinterest-pins-bundle.zip';
      link.click();
      URL.revokeObjectURL(url);
      
      toast.success('All pins downloaded as ZIP!');
    } catch (error) {
      console.error('ZIP download error:', error);
      toast.error('Failed to create ZIP file');
    }
  };

  if (isGenerating || pins.length === 0) {
    return (
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <Card className="shadow-lg border-0">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <ImageIcon className="w-5 h-5 text-primary" />
              Generated Pins
            </CardTitle>
          </CardHeader>
          <CardContent>
            {isGenerating ? (
              <div className="text-center py-12 space-y-6">
                <div className="w-20 h-20 mx-auto gradient-primary rounded-3xl flex items-center justify-center animate-pulse">
                  <Loader2 className="w-10 h-10 text-primary-foreground animate-spin" />
                </div>
                <div className="space-y-2">
                  <h3 className="text-lg font-semibold">Generating your pins...</h3>
                  <p className="text-muted-foreground">
                    Creating AI-powered Pinterest visuals
                  </p>
                </div>
                <div className="max-w-xs mx-auto space-y-2">
                  <Progress value={progress} className="h-2" />
                  <p className="text-sm text-muted-foreground">
                    {Math.round(progress)}% complete
                  </p>
                </div>
              </div>
            ) : (
              <div className="text-center py-12 text-muted-foreground">
                <ImageIcon className="w-12 h-12 mx-auto mb-4 opacity-50" />
                <p>Your generated pins will appear here</p>
              </div>
            )}
          </CardContent>
        </Card>
      </motion.div>
    );
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="space-y-6"
    >
      <Card className="shadow-lg border-0">
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle className="flex items-center gap-2">
              <ImageIcon className="w-5 h-5 text-primary" />
              Generated Pins ({pins.length})
            </CardTitle>
            <Button onClick={downloadAllAsZip} className="gradient-primary">
              <Package className="w-4 h-4 mr-2" />
              Download All (ZIP)
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            <AnimatePresence>
              {pins.map((pin, index) => (
                <PinPreview key={pin.id} pin={pin} index={index} />
              ))}
            </AnimatePresence>
          </div>
        </CardContent>
      </Card>
    </motion.div>
  );
}
